use_frameworks!
platform :ios, '13.0'

target 'LUX_Example' do
  pod 'LUX', :path => '../'
  pod 'PlaygroundVCHelpers', git: 'https://github.com/ThryvInc/playground-vc-helpers'
  pod 'FunNet/Combine', git: 'https://github.com/schrockblock/funnet'
  pod 'LithoOperators', git: 'https://github.com/ThryvInc/LithoOperators'
  pod 'FlexDataSource', git: 'https://github.com/ThryvInc/flex-data-source'
  pod 'fuikit', git: 'https://github.com/ThryvInc/fuikit'
  
  target 'LUX_Tests' do
    inherit! :search_paths

    
  end
end
